version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: microblog_development
      POSTGRES_USER: microblog
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  pg_data:
